@path = localhost:3002

GET http://{{path}}/v1/health
Content-Type: application/json

###
GET http://{{path}}/v1/tickets
Content-Type: application/json

###
GET http://{{path}}/v1/tickets/862ed2ba-d983-43fb-95a8-dd9d3471389b
Content-Type: application/json
