@path = localhost:3000

GET http://{{path}}/v1/health
Content-Type: application/json

###
POST http://{{path}}/v1/create-orders
Content-Type: application/json

{
  "customer_id": "018f6058-66f6-7110-82ac-8fd0034b1367",
  "card": "0000000000000001",
  "amount": 140,
  "currency_code": "BRL",
  "items": [
    {
      "id": "018f6058-66f6-7110-82ac-8fd0034b1367",
      "quantity": 1,
      "unit_price": 140
    }
  ]
}
